# Generated by Django 2.2.5 on 2019-09-22 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0003_auto_20190920_2351'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sign',
            new_name='Users',
        ),
    ]
