# Generated by Django 2.2.5 on 2019-09-22 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0004_auto_20190922_2254'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
