# Generated by Django 2.2.5 on 2019-09-22 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0005_auto_20190922_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='secret_word',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
